### ISSUE TITLE
Make SIMIO a standalone Python package

### ISSUE THREAD

**Issue by jeffjennings** [nicokurtovic/SIMIO#13]
As part of the JOSS review, I appreciate the code is designed to serve as executable functions inside CASA, and I know this would be a bit of a larger effort, but I think it would be highly beneficial if the code were also available as a standalone Python package (on PyPI and thus installable by pip).

The only major addition to the code's core routines would be a method to interface with measurement sets; you could model this after existing packages (or just make them dependencies and import them) such as [uvplot](https://pypi.org/project/uvplot/) and [visread](https://pypi.org/project/visread/). This would also allow users to use the code with modular CASA (e.g., as is done with [PRIISM](https://github.com/tnakazato/priism#installation-procedure-in-detail)). 

This would also allow you to easily integrate things like tests for the code's core routines, automating processes such as the manual tests described in the [docs](https://simio-continuum.readthedocs.io/en/main/tutorials/testsimio_0.html). This would better address the JOSS review guideline _Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?_.

As a bit of a bigger change (though one that I think would be very useful for users of SIMIO and for code contributors!), this is just a suggestion.

[https://github.com/openjournals/joss-reviews/issues/4942](https://github.com/openjournals/joss-reviews/issues/4942)

**Comment by nicokurtovic** [comment]
Hi Jeff, thanks for the suggestion. 

I have been thinking a lot about this, and at least for this version I would prefer to keep it as an executable. The initial inspiration for the code structure was the hydro-code [FARGO 3D](https://fargo3d.bitbucket.io/index.html), where you work inside the FARGO folder and you can save your setups individually. My thought was to have something similar to FARGO, where you would only need to download SIMIO, and then save the templates and projects individually in a self-contained folder. 

I think since the last CASA 6.X versions, CASA tasks can also be called from the python terminal ([example](https://casadocs.readthedocs.io/en/stable/notebooks/usingcasa.html)), and so a future SIMIO package could be fully integrated in python, but for the current SIMIO I would prefer to keep the folder structure, if possible.

**Comment by jeffjennings** [comment]
Ok, I appreciate you thinking about this. I think ultimately it would benefit users and maintainers of SIMIO if the package is fully self-contained, but the design choice is yours. I added a suggestion about making the nature of SIMIO a bit more clear in the paper in my comment in #3. I'm happy to close this issue otherwise.
