### ISSUE TITLE
"Installation instructions", and especially dependencies, needed

### ISSUE THREAD

**Issue by adeleplunkett** [nicokurtovic/SIMIO#3]
For the JOSS review, https://github.com/openjournals/joss-reviews/issues/4942, please include clear installation instructions.  From the review checklist:

**Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

This will help the user greatly.

**Comment by jeffjennings** [comment]
I agree; for the installation instructions, you could consider moving steps 1 - 4 in the [docs tutorial 1](https://simio-continuum.readthedocs.io/en/main/tutorials/tutorial_1.html) to the [docs install](https://simio-continuum.readthedocs.io/en/main/content/simio_installation.html). 

For the dependencies, a `setup.py` in the top level of the codebase should list all dependencies in the scripts (numpy, etc.).

See #13  for further discussion on both points. 

[https://github.com/openjournals/joss-reviews/issues/4942](https://github.com/openjournals/joss-reviews/issues/4942)

**Comment by nicokurtovic** [comment]
Thank you very much for your suggestions. 

One of the main ideas of the package is to be as simple to use as possible. In its current version, SIMIO does not need any additional dependency to be installed, neither internal installs of the package. The package is ready to use after being downloaded, as long as a template and a project have been included. I moved the first and second step of tutorial 1 to the installation. 

Since the package is executed from the CASA terminal, the python libraries such as numpy or scipy are already included in the python of CASA, and thus the user does not need to install them independently in their own python. I included additional clarification that CASA needs to be installed in order to use SIMIO.

**Comment by jeffjennings** [comment]
I see, thank you for considering this, and for adding the clarification. I think it would still be nice to have the package be standalone, but since the current functionality is what's detailed in the paper, of course that's up to you. But could you be a bit more explicit in the paper that SIMIO is a set of programs designed to be run in CASA? 

I'd suggest something like changing line 34 in the paper from "SIMIO-continuum is a python-based package for CASA" to "SIMIO-continuum is a set of Python modules designed to be executed within a CASA Python environment".

**Comment by adeleplunkett** [comment]
I agree with @jeffjennings suggestion to modify the text slightly to specify this.  

I think that the https://simio-continuum.readthedocs.io/index.html#document-content/simio_installation section is good for installation.  I see that there is a file called requirements.txt.  This would be a list of dependencies that should be outlined, right?

**Comment by nicokurtovic** [comment]
Hi Adele,

The list of dependencies in docs/requirements.txt only applies for the webpage in redthedocs and the compilation of the documentation pdf. The reason this list is so long is because I had to test many things to fix the problem with the rendering of the equations. 

Other than that, the only requirement for SIMIO-continuum should be CASA v5.X or v6.X, as described in the installation instructions.

**Comment by jeffjennings** [comment]
> I see, thank you for considering this, and for adding the clarification. I think it would still be nice to have the package be standalone, but since the current functionality is what's detailed in the paper, of course that's up to you. But could you be a bit more explicit in the paper that SIMIO is a set of programs designed to be run in CASA?
> 
> I'd suggest something like changing line 34 in the paper from "SIMIO-continuum is a python-based package for CASA" to "SIMIO-continuum is a set of Python modules designed to be executed within a CASA Python environment".

Thanks for making this change to the wording in the paper. I'm happy for this issue to be closed when Adele is.
